Added rubocop-rake and rubocop-rspec support
ONLYOFFICE-QA/x2t-testing pull request #273
Opened 2021-08-16 10:22 UTC by l8556

rename Rakefile

2021-08-16 10:49 UTC, ShockwaveNN requested changes
rubocop-rake and rubocop-rspec should be added to

1. Gemfile
2. .rubocop.yml

2021-08-17 14:27 UTC, askonev approved these changes

2021-08-17 19:28 UTC, ShockwaveNN requested changes

2021-08-17 19:28 UTC, ShockwaveNN commented on .rubocop_todo.yml
> +RSpec/EmptyLineAfterHook:
I think this can be easily fixed

2021-08-17 19:28 UTC, ShockwaveNN commented on .rubocop_todo.yml
> +RSpec/HookArgument:
I think this probably can be fixed

2021-08-17 19:28 UTC, ShockwaveNN commented on .rubocop_todo.yml
> +RSpec/HooksBeforeExamples:
I think this can be fixed

2021-08-17 19:28 UTC, ShockwaveNN commented on .rubocop_todo.yml
> +RSpec/PredicateMatcher:
I think this can be fixed

2021-08-17 19:28 UTC, ShockwaveNN commented on .rubocop_todo.yml
> +Rake/Desc:
I think this can be fixed

2021-08-19 15:28 UTC, ShockwaveNN requested changes

2021-08-19 15:28 UTC, ShockwaveNN commented on spec/functional/documents/fodt_to_docx_functional_spec.rb
> +# frozen_string_literal: true to all groups or subsets of all groups defined in the example of groups
Duplicate frozen_string_literal string

2021-08-19 15:28 UTC, ShockwaveNN commented on spec/smoke/convertion_tests_smoke_spec.rb
> +  after do |example|
I think this `after`  block should be places directly after `before` block

2021-08-20 07:43 UTC, ShockwaveNN approved these changes

2021-08-20 07:47 UTC, merged