Skip one file. Because links and images in tables are not supported.
ONLYOFFICE-QA/x2t-testing pull request #301
Opened 2021-09-07 13:59 UTC by l8556

2021-09-07 14:04 UTC, askonev reviewed
Please, add a link to the bug on bugzilla into summary

2021-09-07 16:32 UTC, ShockwaveNN requested changes
`skip('https:...')` in `(..)` is better for readablity and in common with our code style

2021-09-07 16:44 UTC, ShockwaveNN approved these changes

2021-09-08 09:25 UTC, askonev approved these changes

2021-09-08 09:50 UTC, merged