Added conversion with parameters from xml file
ONLYOFFICE-QA/x2t-testing pull request #510
Opened 2022-04-04 11:51 UTC by l8556

2022-04-07 12:33 UTC, ShockwaveNN requested changes

2022-04-07 12:33 UTC, ShockwaveNN commented on data/static_data.rb
> +  PARAM_XML_PATH = "#{File.join(File.dirname(__FILE__), '/..')}/assets/parameters.xml"
I think it's not used any more

2022-04-07 12:33 UTC, ShockwaveNN commented on data/static_data.rb
> +  FORMAT_NUMBERS = {
I think some description is needed - why those numbers
For example link to `core` source lines or maybe some source of this number (Like "Those data from Oleg Korshul`)

2022-04-07 12:33 UTC, ShockwaveNN commented on spec/spec_helper.rb
> +def xml
I think those lines should not be in `spec_helper` but you can place it in `framework/x2t.rb`

2022-04-07 12:33 UTC, ShockwaveNN commented on framework/xml_helper.rb
> +  # @param [String] format is a format for conversion
Add that it will return? in docs

2022-04-07 12:33 UTC, ShockwaveNN commented on framework/xml_helper.rb
> +        xml.m_sFileFrom source_filepath
I think we mostly use code style like 
```
xml.m_sFileFrom(source_filepath)
```

Sadly rubocop didn't catch that

2022-04-07 13:45 UTC, ShockwaveNN requested changes

2022-04-07 13:45 UTC, ShockwaveNN commented on data/static_data.rb
> +  FORMAT_NUMBERS = {
I also think since those FORMAT_NUMBER are used only in XmlParams - this constant should be placed in this file, and not in static data

2022-04-07 15:16 UTC, ShockwaveNN requested changes

2022-04-08 15:47 UTC, ShockwaveNN requested changes

2022-04-08 15:47 UTC, ShockwaveNN commented on .github/workflows/unit_test.yml
> +        run: rspec ./spec/unit/xml_params_spec.rb
Never run a single spec, you defenetly to forgot add new spec in config after you add new spec for some reason

Use
```
rspec spec/unit
```

2022-04-08 15:47 UTC, ShockwaveNN commented on spec/unit/xml_params_spec.rb
> +  xml_template = File.open('./spec/unit/template.xml') { |f| Nokogiri::XML(f) }
I think it's not a template.xml but `simple_sample.xml` is better name

2022-04-08 15:47 UTC, ShockwaveNN commented on spec/unit/xml_params_spec.rb
> +  source_filepath = './tmp/86476809/(NS)-CHAUZIMU-MWA-CHILENGEDWE.doc'
For unit tests I think we can safely remove those complicated values and replace them with something like

```
source_filepath = '/source/file.doc
```

And similar to `converted_filepath`

2022-04-08 15:47 UTC, ShockwaveNN commented on spec/unit/xml_params_spec.rb
> +    expect(created_xml.to_xml).to eq(xml_template.to_xml)
I think we don't need to parse template file with nokogiri

I think we should

1. Create result XML
2. File.read both template and result xmls and compare their like strings, it's simpler

2022-04-08 15:47 UTC, ShockwaveNN commented on spec/unit/xml_params_spec.rb
> +    expect(created_xml.at('m_nFormatTo').content).to eq('65')
I think 65 is better to replace with `FORMAT_NUMBERS[format]`

2022-04-08 15:47 UTC, ShockwaveNN commented on spec/unit/xml_params_spec.rb
> +  created_xml = File.open(xml.create_xml(source_filepath, converted_filepath, format)) { |f| Nokogiri::XML(f) }
`parsed_result` is better name, because is not `created` but also `parsed` via Nokogiri

2022-04-08 16:22 UTC, ShockwaveNN approved these changes

2022-04-09 13:10 UTC, askonev approved these changes

2022-04-11 09:48 UTC, merged